const projects  = [
    { "path": 'images/projects/bedroom/1.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/2.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/3.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/4.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/5.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/6.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/7.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/8.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/9.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/10.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/11.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/12.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/13.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/14.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/15.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},   
    { "path": 'images/projects/living-room/1.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/2.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/3.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/4.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/5.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/6.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/7.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/8.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/9.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/10.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/11.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/12.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/13.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/14.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},   
    { "path": 'images/projects/living-room/1.jpg',"title": "Living Room" ,"type":"living-room", "category": "Civil Work"},
    { "path": 'images/projects/living-room/2.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/3.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/4.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/5.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/6.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/7.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/8.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/9.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/10.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/11.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/12.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/13.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/14.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},   
    { "path": 'images/projects/kitchen/1.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/2.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/3.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/4.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/5.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/6.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/7.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/8.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/9.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/bathroom/1.jpg',"title": "Bathroom" ,"type":"bathroom", "category": "Bathroom"},
    { "path": 'images/projects/bathroom/2.jpg',"title": "Bathroom" ,"type":"bathroom", "category": "Bathroom"},
    { "path": 'images/projects/bathroom/3.jpg',"title": "Bathroom" ,"type":"bathroom", "category": "Bathroom"},
    { "path": 'images/projects/bathroom/4.jpg',"title": "Bathroom" ,"type":"bathroom", "category": "Bathroom"},
    { "path": 'images/projects/terrace/1.jpg',"title": "Terrace" ,"type":"terrace", "category": "Terrace"},
];

const projectsHome  = [
    { "path": 'images/projects/bedroom/1.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/bedroom/12.jpg',"title": "Bedroom" ,"type":"bedroom", "category": "Bedroom"},
    { "path": 'images/projects/living-room/1.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/living-room/12.jpg',"title": "Living Room" ,"type":"living-room", "category": "Living Room"},
    { "path": 'images/projects/kitchen/1.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/kitchen/5.jpg',"title": "Kitchen" ,"type":"kitchen", "category": "Kitchen"},
    { "path": 'images/projects/bathroom/1.jpg',"title": "Bathroom" ,"type":"bathroom", "category": "Bathroom"},
    { "path": 'images/projects/terrace/1.jpg',"title": "Terrace" ,"type":"terrace", "category": "Terrace"},
    { "path": 'images/projects/civil-work/5.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
    { "path": 'images/projects/civil-work/13.jpg',"title": "Civil Work" ,"type":"civil-work", "category": "Civil Work"},
];